### ISSUE TITLE
How to style with method?

### ISSUE THREAD

**Issue by matibzurovski** [robertwijas/UISS#45]
I am being able to modify components through properties, but I need to modify a UIBarItem with this method: 

-(void)setTitleTextAttributes:(NSDictionary *)attributes forState:(UIControlState)state NS_AVAILABLE_IOS(5_0) UI_APPEARANCE_SELECTOR;

I have not found any example that indicates how should the JSON look, and everything I have tried does not compile.

Thanks in advance

**Comment by robertwijas** [comment]
There's an example for UITabBarItem in [the style](https://github.com/robertwijas/UISS/blob/master/Project/UISSDemo/UISS/uiss.json) for the Demo app.

**Comment by robertwijas** [comment]
@matibzurovski let me know if it works for you. Thank you!

**Comment by matibzurovski** [comment]
Not really, I am getting an error for the following code:

 "UINavigationBar": {
    "tintColor": "white",
    "barTintColor": [254, 0, 26],
    "titleTextAttributes:normal": {
        "textColor": "green"
     }
 }

![screen shot 2015-05-18 at 12 37 40 pm](https://cloud.githubusercontent.com/assets/9628833/7684213/bbeb63ca-fd5a-11e4-8933-8abe6473f577.png)

**Comment by robertwijas** [comment]
Your snippet set the property for UINavigationBar, which has a simple `titleTextAttributes` without control state parameter.

I'm guessing you want to change properties for UIBarButtonItem contained in UINavigationBar:
```json
"UINavigationBar": {
  "tintColor": "white",
  "barTintColor": [254, 0, 26],
  "UIBarButtonItem": {
    "titleTextAttributes:normal": {
      "textColor": "green"
    }
  }
}
```

**Comment by matibzurovski** [comment]
That will change the color of the buttons from the bar. I want to change the color of the title of the bar. Thanks

**Comment by robertwijas** [comment]
In that case you should remove control state param:

```json
"UINavigationBar": {
  "tintColor": "white",
  "barTintColor": [254, 0, 26],
  "titleTextAttributes": {
    "textColor": "green"
  }
}
```

because:

```objc
@interface UINavigationBar
...
@property(nonatomic, copy) NSDictionary *titleTextAttributes
```

**Comment by matibzurovski** [comment]
That did the trick, thanks very much!

**Comment by matibzurovski** [comment]
How do I change the properties of an UIImage. I am able to change the textColor and font of a UILabel, but not the tintColor of a UIImage. Thanks

"OwnViewController" : {
	"UILabel": {
		"textColor": "green",
                "font": ["Copperplate-Bold", 18]
    },
    "UIImage" : {
    	"tintColor": "green"
    }
},

**Comment by robertwijas** [comment]
UIImage doesn't support UIAppearance, but UIImageView does.

**Comment by matibzurovski** [comment]
One last thing: I want to customize my navigation bar so that the color of the letters are white and the barTintColor is red. However, I would like to make the top part of the bar green, where Wifi signal, clock and battery percentage are displayed. What should I add to this code?

"UINavigationBar": {
  "tintColor": "white",
  "barTintColor": "red"
}

Thanks for your help!

**Comment by robertwijas** [comment]
I think the only way to achieve this is to prepare an image which has top 20px green (for status bar background) and the bottom 44px red (for navigation bar background). Use _backgroundImage:default_ property.

For the title color use _titleTextAttributes_.

**Comment by matibzurovski** [comment]
With titleTextAttributes I can change the color of the navigation bar title. Any way to change the color of the time, wifi and battery?

**Comment by robertwijas** [comment]
It can only be black or white. Read about `UIViewController.preferredStatusBarStyle`.

**Comment by matibzurovski** [comment]
How would be the code to set it white?

**Comment by robertwijas** [comment]
You cannot use UIAppearance to set that. Read about the method I mentioned above.

**Comment by matibzurovski** [comment]
Ok, thanks.
Last one for the day :) 
Is it possible to change the barTintColor of a UINavigationItem?

**Comment by robertwijas** [comment]
No.
